In [1]:
import numpy as np

x = np.array([[1, 2, 3],[4, 5, 6]])
print(x.dtype)
print(x.shape)


y = np.array([[4.3, 3.2], [5.6 , 6.3], [5.3, 4.1]])
print(y.dtype)
print(y.shape)


z = np.array([[False, False, True],[True, False, False],[True, False, True]])
print(z.dtype)
print(z.shape)

int32
(2, 3)
float64
(3, 2)
bool
(3, 3)


In [ ]:
import numpy as np

x = np.array([[1, 2, 3],[4, 5, 6]])
print(x[1,2])
print(x[:,1])

y = np.array([[4.3, 3.2], [5.6 , 6.3], [5.3, 4.1]])
print(y[2,1])
print(y[:,1])

z = np.array([[False, False, True],[True, False, False],[True, False, True]])
print(z[1,2])
print(z[:,1])

In [1]:
import numpy as np

x1 = np.zeros((2,3), dtype=int)
print(x1)

x2 = np.ones((4,3), dtype=int)
print(x2)

y1 = np.zeros((2,3), dtype=float)
print(y1)

y2 = np.ones((4,3), dtype=float)
print(y2)

z1 = np.zeros((2,3), dtype=bool)
print(z1)

z2 = np.ones((4,3), dtype=bool)
print(z2)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import numpy as np

matrix = np.zeros((10,3), dtype=float)
print(matrix)

In [2]:
import numpy as np

a = np.array([[.7, .2, .1],[.3, .6, .1],[.5, .1, .4]])
b = np.array([[.8, .3, .5],[.1, .4, .1],[.1, .3, .4]])
c = np.zeros((3,3), dtype=float)

rijen = a.shape[0]
kolommen = a.shape[1]

for i in range (rijen):
    for j in range (kolommen):
        c[i][j] = a[i][j] + b [i][j]
        
print(c)

[[1.5 0.5 0.6]
 [0.4 1.  0.2]
 [0.6 0.4 0.8]]


In [3]:
import numpy as np

a = np.array([[.7, .2, .1],[.3, .6, .1],[.5, .1, .4]])
b = np.array([[.8, .3, .5],[.1, .4, .1],[.1, .3, .4]])
c = np.zeros((3,3), dtype=float)

dimensie = a.shape[0]

for i in range (dimensie):
    for j in range (dimensie):
        for k in range (dimensie):
            c[i][j] = c[i][j] + a[i][k] * b [k][j]
        
print(c)

[[0.59 0.32 0.41]
 [0.31 0.36 0.25]
 [0.45 0.31 0.42]]


In [4]:
import numpy as np
from random import random

def initialiseerBommentapijt(m, n, p):
    bommen = np.zeros((m, n), dtype=bool)
    for i in range(m):
        for j in range(n):
            rand  = random();
            if (rand < p):
                bommen[i][j] = True
            else:
                bommen[i][j] = False
    return bommen

def initialiseerBurenMatrix(bommentapijt):
    matrixAantallen = np.zeros((m, n), dtype=int)
    for i in range(m):
        for j in range(n):
            if (bommentapijt[i][j]):
                matrixAantallen[i][j] = -1
            else:
                matrixAantallen[i][j] = 0
                for x in range(i-1, i+2, 1):
                    for y in range(j-1, j+2, 1):
                        if (x >= 0 and  x < m and y >=0 and y < n):
                            if(bommentapijt[x][y]):
                                matrixAantallen[i][j] += 1
    return matrixAantallen                

def drukBommentapijt(bommentapijt):
    for i in range(m):
        for j in range(n):
            if (bommentapijt[i][j]):
                print("* ", end = "")
            else:
                print(". ", end = "")
        print()
    print()
        
        
def drukBurenMatrix(matrixAantallen):
    for i in range(m):
        for j in range(n):
            if (burenMatrix[i][j] == -1):
                print("* ", end = "")
            else:
                print(matrixAantallen[i][j], end = " ")
        print()
    print()
        
m = int(input("Geef aantal rijen:"))
n = int(input("Geef aantal kolommen:"))
p = float(input("Geef probabiliteit p in:"))

bommenTapijt = initialiseerBommentapijt(m, n, p)
drukBommentapijt(bommenTapijt)
burenMatrix = initialiseerBurenMatrix(bommenTapijt)
drukBurenMatrix(burenMatrix)


Geef aantal rijen:19
Geef aantal kolommen:12
Geef probabiliteit p in:0.3
. . . . * . . . * . . . 
* . * . * . . . . . * . 
* . * . . . * . * . . . 
. . . . . . . . * . . . 
* . . . * . * * . . . . 
. . . . . * . * * * . . 
. . . * . . * * . * . * 
* . * . . . . . . . * . 
. * . . . . * . . . . . 
. . . . . . . * . . * . 
. . . . * . . . * * . . 
. * . . . . . . . * * * 
. . . . * . . * * . . . 
* . * * . . . . * . * . 
. . * . . * . * . . . . 
* * * . * . . . . * . . 
. * * . . . . * . * . . 
. . . . * . * . . . . . 
. * . . . . . . * . * . 

1 2 1 3 * 2 0 1 * 2 1 1 
* 4 * 4 * 3 1 3 2 3 * 1 
* 4 * 3 1 2 * 3 * 3 1 1 
2 3 1 2 1 3 3 5 * 2 0 0 
* 1 0 1 * 3 * * 5 3 1 0 
1 1 1 2 3 * 6 * * * 3 1 
1 2 2 * 2 2 * * 5 * 4 * 
* 3 * 2 1 2 3 3 2 2 * 2 
2 * 2 1 0 1 * 2 1 2 2 2 
1 1 1 1 1 2 2 * 3 3 * 1 
1 1 1 1 * 1 1 2 * * 5 3 
1 * 1 2 2 2 1 3 5 * * * 
2 3 3 3 * 1 1 * * 5 4 3 
* 3 * * 3 2 3 4 * 3 * 1 
3 6 * 5 3 * 2 * 3 3 2 1 
* * * 4 * 2 3 2 4 * 2 0 
3 * * 4 2 3 2 * 3 * 2 0 
2 3 3 2 * 2 * 3 3 3 2 1 
1